routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('splade')->group(function () {
    // Registers routes to support password confirmation in Form and Link components...
    Route::spladePasswordConfirmation();

    // Registers routes to support Table Bulk Actions and Exports...
    Route::spladeTable();

    // Registers routes to support async File Uploads with Filepond...
    Route::spladeUploads();

    Route::get('/', function () {
        return view('welcome');
    });

    Route::middleware('auth')->group(function () {
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->middleware(['verified'])->name('dashboard');

        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

        Route::resource('posts', PostController::class);
        Route::resource('categories', CategoryController::class);
    });

    require __DIR__ . '/auth.php';
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use App\Tables\Categories;
use ProtoneMedia\Splade\Facades\Toast;

class CategoryController extends Controller
{
    public function index()
    {
        return view('categories.index', [
            'categories' => Categories::class
        ]);
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(CategoryRequest $request)
    {
        Category::create($request->validated());

        Toast::title('New category created successfully!')->autoDismiss(3);

        return to_route('categories.index');
    }

    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    public function update(CategoryRequest $request, Category $category)
    {
        $category->update($request->validated());

        Toast::title('Category ' . $category->name . ' updated successfully!')->autoDismiss(3);

        return to_route('categories.index');
    }

    public function destroy(Category $category)
    {
        $destroy_category = $category->name;
        $category->delete();

        Toast::title('Category ' . $destroy_category . ' has been deleted!')->autoDismiss(3);

        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Tables\Posts;
use ProtoneMedia\Splade\Facades\Toast;

class PostController extends Controller
{
    public function index()
    {
        return view('posts.index', [
            'posts' => Posts::class
        ]);
    }

    public function create()
    {
        $categories = Category::pluck('name', 'id')->toArray();
        return view('posts.create', compact('categories'));
    }

    public function store(PostRequest $request)
    {
        Post::create($request->validated());

        Toast::title('New post created successfully!');

        return to_route('posts.index');
    }

    public function edit(Post $post)
    {
        $categories = Category::pluck('name', 'id')->toArray();
        return view('posts.edit', compact('post', 'categories'));
    }

    public function update(PostRequest $request, Post $post)
    {
        $post->update($request->validated());

        Toast::title('Post ' . $post->title . ' updated successfully!');

        return to_route('posts.index');
    }

    public function destroy(Post $post)
    {
        $destroy_post = $post->title;
        $post->delete();

        Toast::title('Post ' . $destroy_post . ' has been deleted!')->autoDismiss(3);

        return redirect()->back();
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;

class ProfileController extends Controller
{
    /**
     * Display the user's profile form.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function edit(Request $request)
    {
        return view('profile.edit', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Update the user's profile information.
     *
     * @param  \App\Http\Requests\ProfileUpdateRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProfileUpdateRequest $request)
    {
        $request->user()->fill($request->validated());

        if ($request->user()->isDirty('email')) {
            $request->user()->email_verified_at = null;
        }

        $request->user()->save();

        return Redirect::route('profile.edit')->with('status', 'profile-updated');
    }

    /**
     * Delete the user's account.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Request $request)
    {
        $request->validateWithBag('userDeletion', [
            'password' => ['required', 'current-password'],
        ]);

        $user = $request->user();

        Auth::logout();

        $user->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return Redirect::to('/');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/categories/create.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="flex items-center justify-between">
         <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Categories') }}
         </h2>
      </div>
   </x-slot>

   <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

         <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
            <div class="max-w-xl">
               <x-splade-form :action="route('categories.store')" class="max-w-2xl mx-auto">
                  <x-splade-input name="name" label="Name" />

                  <x-splade-input name="slug" label="Slug" class="mt-2" />

                  <x-splade-submit class="mt-4" />
               </x-splade-form>
            </div>
         </div>

      </div>
   </div>
</x-app-layout>

resources/views/categories/edit.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="flex items-center justify-between">
         <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Categories') }}
         </h2>
      </div>
   </x-slot>

   <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

         <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
            <div class="max-w-xl">
               <x-splade-form :action="route('categories.update', $category)" :default="$category" method="put" class="max-w-2xl mx-auto">
                  <x-splade-input name="name" label="Name" />

                  <x-splade-input name="slug" label="Slug" class="mt-2" />

                  <x-splade-submit class="mt-4" />
               </x-splade-form>
            </div>
         </div>

      </div>
   </div>
</x-app-layout>

resources/views/categories/index.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="flex items-center justify-between">
         <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Categories') }}
         </h2>

         <Link href="{{ route('categories.create') }}"
            class="px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white font-semibold rounded-md">
         New Category
         </Link>
      </div>
   </x-slot>

   <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

         <x-splade-table :for="$categories">
            @cell('action', $category)
               <Link href="{{ route('categories.edit', $category) }}"
                  class="text-xs text-indigo-600 hover:text-indigo-700 font-bold tracking-wider uppercase">
               Edit
               </Link>
               <Link confirm="Enter the danger zone..." confirm-text="Are you sure?" confirm-button="Yes, take me there!"
                  cancel-button="No, keep me save!" href="{{ route('categories.destroy', $category) }}" method="DELETE"
                  class="text-xs text-red-500 hover:text-red-700 font-bold tracking-wider uppercase" preserve-scroll>
               Delete
               </Link>
            @endcell
         </x-splade-table>

      </div>
   </div>
</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<div class="min-h-screen bg-gray-100">
    @include('layouts.navigation')

    <!-- Page Heading -->
    <header class="bg-white shadow">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            {{ $header }}
        </div>
    </header>

    <!-- Page Content -->
    <main>
        {{ $slot }}
    </main>
</div>

resources/views/layouts/guest.blade.php
<div class="font-sans text-gray-900 antialiased">
    {{ $slot }}
</div>

resources/views/layouts/navigation.blade.php
<x-splade-toggle>
   <nav class="bg-white border-b border-gray-100">
      <!-- Primary Navigation Menu -->
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
         <div class="flex justify-between h-16">
            <div class="flex">
               <!-- Logo -->
               <div class="shrink-0 flex items-center">
                  <Link href="{{ route('dashboard') }}">
                  <x-application-logo class="block h-9 w-auto fill-current text-gray-800" />
                  </Link>
               </div>

               <!-- Navigation Links -->
               <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                  <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                     {{ __('Dashboard') }}
                  </x-nav-link>
                  <x-nav-link :href="route('posts.index')" :active="request()->routeIs('posts.index')">
                     {{ __('Post') }}
                  </x-nav-link>
                  <x-nav-link :href="route('categories.index')" :active="request()->routeIs('categories.index')">
                     {{ __('Category') }}
                  </x-nav-link>
               </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
               <x-dropdown placement="bottom-end">
                  <x-slot name="trigger">
                     <button
                        class="flex items-center text-sm font-medium text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition duration-150 ease-in-out">
                        <div>{{ Auth::user()->name }}</div>

                        <div class="ml-1">
                           <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                              <path fill-rule="evenodd"
                                 d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                 clip-rule="evenodd" />
                           </svg>
                        </div>
                     </button>
                  </x-slot>

                  <x-slot name="content">
                     <x-dropdown-link :href="route('profile.edit')">
                        {{ __('Profile') }}
                     </x-dropdown-link>

                     <!-- Authentication -->
                     <form method="POST" action="{{ route('logout') }}">
                        @csrf

                        <x-dropdown-link as="a" :href="route('logout')"
                           onclick="event.preventDefault(); this.closest('form').submit();">
                           {{ __('Log Out') }}
                        </x-dropdown-link>
                     </form>
                  </x-slot>
               </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
               <button @click="toggle"
                  class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                  <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                     <path v-bind:class="{ hidden: toggled, 'inline-flex': !toggled }" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                     <path v-bind:class="{ hidden: !toggled, 'inline-flex': toggled }" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
               </button>
            </div>
         </div>
      </div>

      <!-- Responsive Navigation Menu -->
      <div v-bind:class="{ block: toggled, hidden: !toggled }" class="sm:hidden">
         <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
               {{ __('Dashboard') }}
            </x-responsive-nav-link>
         </div>

         <!-- Responsive Settings Options -->
         <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
               <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
               <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
               <x-responsive-nav-link :href="route('profile.edit')">
                  {{ __('Profile') }}
               </x-responsive-nav-link>

               <!-- Authentication -->
               <form method="POST" action="{{ route('logout') }}">
                  @csrf

                  <x-responsive-nav-link as="a" :href="route('logout')"
                     onclick="event.preventDefault(); this.closest('form').submit();">
                     {{ __('Log Out') }}
                  </x-responsive-nav-link>
               </form>
            </div>
         </div>
      </div>
   </nav>
</x-splade-toggle>

resources/views/posts/create.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="flex items-center justify-between">
         <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Post') }}
         </h2>
      </div>
   </x-slot>

   <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

         <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
            <div class="max-w-xl">
               <x-splade-form :action="route('posts.store')" class="max-w-2xl mx-auto">

                  <x-splade-select name="category_id" :options="$categories" label="Category" />

                  <x-splade-input name="title" label="Title" class="mt-2" />

                  <x-splade-input name="slug" label="Slug" class="mt-2" />

                  <x-splade-textarea name="description" label="Description" class="mt-2" autosize />

                  <x-splade-submit class="mt-4" />
               </x-splade-form>
            </div>
         </div>

      </div>
   </div>
</x-app-layout>

resources/views/posts/edit.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="flex items-center justify-between">
         <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Post') }}
         </h2>
      </div>
   </x-slot>

   <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

         <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
            <div class="max-w-xl">
               <x-splade-form :action="route('posts.update', $post)" :default="$post" method="PUT" class="max-w-2xl mx-auto">

                  <x-splade-select name="category_id" :options="$categories" label="Category" />

                  <x-splade-input name="title" label="Title" class="mt-2" />

                  <x-splade-input name="slug" label="Slug" class="mt-2" />

                  <x-splade-textarea name="description" label="Description" class="mt-2" autosize />

                  <x-splade-submit class="mt-4" />
               </x-splade-form>
            </div>
         </div>

      </div>
   </div>
</x-app-layout>

resources/views/posts/index.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="flex items-center justify-between">
         <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Posts') }}
         </h2>

         <Link href="{{ route('posts.create') }}"
            class="px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white font-semibold rounded-md">
         New Post
         </Link>
      </div>
   </x-slot>

   <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

         <x-splade-table :for="$posts">
            @cell('action', $post)
               <Link href="{{ route('posts.edit', $post->id) }}"
                  class="text-xs text-indigo-600 hover:text-indigo-700 font-bold tracking-wider uppercase">
               Edit
               </Link>
               <Link confirm="Enter the danger zone..." confirm-text="Are you sure?" confirm-button="Yes, take me there!"
                  cancel-button="No, keep me save!" href="{{ route('posts.destroy', $post) }}" method="DELETE"
                  class="text-xs text-red-500 hover:text-red-700 font-bold tracking-wider uppercase" preserve-scroll>
               Delete
               </Link>
            @endcell
         </x-splade-table>

      </div>
   </div>
</x-app-layout>

resources/views/root.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="csrf-token" content="{{ csrf_token() }}">

   <title>{{ config('app.name', 'Laravel') }}</title>

   <!-- Fonts -->
   <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@200;300;400;500;600;700&display=swap">

   <!-- Scripts -->
   @vite(['resources/js/app.js'])
   @spladeHead
</head>

<body class="font-sans antialiased">
   @splade
</body>

</html>